<a href="https://colab.research.google.com/github/hyojunyee/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/Task%20/Task_0527_%ED%92%80%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task1_0527. 4개의 Series를 결합하여 데이터프레임을 생성하여 출력하세요.
- 출력한 데이터프레임에서 추출하고 싶은 5개의 데이터를 인덱싱하여 출력
- null값을 3개 추가
- null값의 개수를 확인하고 삭제
- 2개의 데이터를 수정
- 1개의 행을 삭제

In [13]:
import pandas as pd
import numpy as np

# 4개의 Series 생성
s1 = pd.Series(['kim', 'lee', 'park', 'yoon', 'ryu'], name='이름')
s2 = pd.Series([22, 35, 27, 29, 30], name='나이')
s3 = pd.Series([1, 2, 1, 1, 2], name='성별')
s4 = pd.Series(['seoul', 'seoul', 'degu', 'busan', 'seoul'], name='주소')

In [14]:
# 데이터프레임 생성
df = pd.concat([s1, s2, s3, s4], axis=1)
print("Original DataFrame:")
print(df)

Original DataFrame:
     이름  나이  성별     주소
0   kim  22   1  seoul
1   lee  35   2  seoul
2  park  27   1   degu
3  yoon  29   1  busan
4   ryu  30   2  seoul

In [15]:
# 5개의 데이터를 인덱싱하여 출력
indexed_data = df.loc[0:4, ['이름', '성별']]
print("\nIndexed Data (5 items):")
print(indexed_data)

Indexed Data (5 items):
     이름  성별
0   kim   1
1   lee   2
2  park   1
3  yoon   1
4   ryu   2

In [16]:
# null 값을 3개 추가
df.loc[1, '주소'] = np.nan
df.loc[2, '나이'] = np.nan
df.loc[3, '성별'] = np.nan
print("\nDataFrame with null values added:")
print(df)

DataFrame with null values added:
     이름    나이   성별     주소
0   kim  22.0  1.0  seoul
1   lee  35.0  2.0    NaN
2  park   NaN  1.0   degu
3  yoon  29.0  NaN  busan
4   ryu  30.0  2.0  seoul

In [17]:
# null 값의 개수를 확인
null_count = df.isnull().sum().sum()
print("\nNumber of null values:", null_count)

Number of null values: 3

In [18]:
#  null 값을 삭제
df_cleaned = df.dropna()
print("\nDataFrame after dropping null values:")
print(df_cleaned)

DataFrame after dropping null values:
    이름    나이   성별     주소
0  kim  22.0  1.0  seoul
4  ryu  30.0  2.0  seoul

In [19]:
# 2개의 데이터를 수정
df_cleaned.loc[0, '이름'] = 'seo'
df_cleaned.loc[4, '나이'] = 27
print("\nDataFrame after modifying 2 values:")
print(df_cleaned)

DataFrame after modifying 2 values:
    이름    나이   성별     주소
0  seo  22.0  1.0  seoul
4  ryu  27.0  2.0  seoul

In [20]:
# 1개의 행을 삭제
df_cleaned = df_cleaned.drop(4)
print("\nDataFrame after deleting 1 row:")
print(df_cleaned)

DataFrame after deleting 1 row:
    이름    나이   성별     주소
0  seo  22.0  1.0  seoul

In [ ]:
# 강사님 풀이

In [ ]:
import numpy as np
import pandas as pd

# 데이터프레임 생성
id = np.arange(1, 1001)
i1 = pd.Series(id)
gender = np.random.randint(2, size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1, 101, size=1000)
a1 = pd.Series(age)
region = np.random.randint(1, 11, size=1000)
r1 = pd.Series(region)
df = pd.concat([i1, g1, a1, r1], axis=1)
df.rename(columns={0: 'id', 1: 'gender', 2: 'age', 3: 'region'}, inplace=True)

In [ ]:
# 데이터프레임에서 추출하고 싶은 5개의 데이터를 인덱싱하여 출력
print(df.iloc[[0, 1, 2, 3, 4]])

In [ ]:
# null값을 3개 추가
df.loc[0, 'age'] = np.nan
df.loc[1, 'gender'] = np.nan
df.loc[2, 'region'] = np.nan

In [ ]:
# null값의 개수를 확인하고 삭제
null_counts = df.isnull().sum()
print( null_counts,'\n')
df.dropna(inplace=True)
print(df.head(7))

In [ ]:
# 2개의 데이터를 수정
df.loc[3, 'age'] = 50
df.loc[4, 'region'] = 5

In [ ]:
# 1개의 행을 삭제
df.drop(index=5, inplace=True)

In [ ]:
# 최종 데이터프레임 출력
print(df.head(7))

Task2_0527. 학생별 성적 데이터셋으로 의미있게 데이터 셋을 수정하세요.(아래 사항 반영)
- S1 ~ S10은 평균 점수를 기준으로 1등급에서 10등급이고 등급간 점수 차는 5점
- 결시자가 국어 3명, 수학 2명 있음
- 영어, 수학의 평균 점수가 국어 대비 5점 낮음

In [28]:
import pandas as pd
import numpy as np
df = np.random.randint(1,5,size=(10,5))
df=pd.DataFrame(df,index=['s1','s2','s3','s4','s5','s6','s7','s8','s9','s10'],
               columns=['국어','영어','수학','과학','사회'])
df

# 등급간 점수 차는 5점
for i in range(10):
    df.iloc[i] = 90 - i*5
df

# 영어, 수학의 평균점수가 국어대비 5점 낮음
df['영어'] = df['국어'] - 5
df['수학'] = df['국어'] - 5

# 결시자 반영 (결시자는 -1로 표시)
df.loc[np.random.choice(df.index, 3, replace=False), '국어'] = '결시자'
df.loc[np.random.choice(df.index, 2, replace=False), '수학'] = '결시자'

df

      국어  영어   수학  과학  사회
s1   결시자  85   85  90  90
s2    85  80  결시자  85  85
s3    80  75   75  80  80
s4   결시자  70   70  75  75
s5    70  65   65  70  70
s6   결시자  60  결시자  65  65
s7    60  55   55  60  60
s8    55  50   50  55  55
s9    50  45   45  50  50
s10   45  40   40  45  45

In [ ]:
# 강사님 풀이

In [22]:
import pandas as pd
import numpy as np
df = np.random.randint(1,5,size=(10,5))
df=pd.DataFrame(df,index=['s1','s2','s3','s4','s5','s6','s7','s8','s9','s10'],
               columns=['국어','영어','수학','과학','사회'])

In [23]:
# 등급간 점수 차는 5점
for i in range(10):
    df.iloc[i] = 90 - i*5
df

     국어  영어  수학  과학  사회
s1   90  90  90  90  90
s2   85  85  85  85  85
s3   80  80  80  80  80
s4   75  75  75  75  75
s5   70  70  70  70  70
s6   65  65  65  65  65
s7   60  60  60  60  60
s8   55  55  55  55  55
s9   50  50  50  50  50
s10  45  45  45  45  45

In [24]:
# 영어, 수학의 평균점수가 국어대비 5점 낮음
# df.iloc[i,1:3] 영어 수학점수는 df.iloc[i,0] 국어에서 -5점
for i in range(10):
    df.iloc[i,1:3] = df.iloc[i,0] - 5
df

     국어  영어  수학  과학  사회
s1   90  85  85  90  90
s2   85  80  80  85  85
s3   80  75  75  80  80
s4   75  70  70  75  75
s5   70  65  65  70  70
s6   65  60  60  65  65
s7   60  55  55  60  60
s8   55  50  50  55  55
s9   50  45  45  50  50
s10  45  40  40  45  45

In [25]:
# 결시자가 국어 3 명, 수학 2명 있음
a = df.copy()
a.iloc[7:,0] = np.nan
a.iloc[8:,2] = np.nan
a

       국어  영어    수학  과학  사회
s1   90.0  85  85.0  90  90
s2   85.0  80  80.0  85  85
s3   80.0  75  75.0  80  80
s4   75.0  70  70.0  75  75
s5   70.0  65  65.0  70  70
s6   65.0  60  60.0  65  65
s7   60.0  55  55.0  60  60
s8    NaN  50  50.0  55  55
s9    NaN  45   NaN  50  50
s10   NaN  40   NaN  45  45

Task3_0527. df1에서 결측값 처리 후 딕셔너리, 리스트로 변환하여 출력하세요.

In [44]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Math": [85, np.nan, 88, 90, 76],
    "English": [92, 85, 89, np.nan, 80],
    "Science": [78, 90, 95, 85, 89],
    "History": [88, 92, 85, 91, np.nan]
})

# 결측값에 0을 채워넣음
df2 = df1.copy()
for column in columns:
    df2[column].fillna(df2[column].mean(),inplace=True)

# 배열로 변환
df1_arr = df2.to_numpy()
print(df1_arr)

# 딕셔너리 변환
df1_dict = df2.to_dict()
print(df1_dict)

# 데이터프레임은 여러 행과 열로 구성된 구조를 가지고 있으며, 각 셀에는 데이터 값이 저장됨
# tolist() 함수는 데이터프레임을 리스트 형태로 변환하는 함수이지만, 리스트는 1차원 구조만을 지원
# 따라서, 다차원 구조인 데이터프레임을 직접 리스트로 변환하려고 하면 오류가 발생
# df1_list = df2.value.tolist()
# print(df1_list)

# 리스트 변환
df1_list = [list(value) for value in df1_dict.values()]
print(df1_list)

[['Alice' 85.0 92.0 78 88.0]
 ['Bob' 84.75 85.0 90 92.0]
 ['Charlie' 88.0 89.0 95 85.0]
 ['David' 90.0 86.5 85 91.0]
 ['Eve' 76.0 80.0 89 89.0]]
{'Name': {0: 'Alice', 1: 'Bob', 2: 'Charlie', 3: 'David', 4: 'Eve'}, 'Math': {0: 85.0, 1: 84.75, 2: 88.0, 3: 90.0, 4: 76.0}, 'English': {0: 92.0, 1: 85.0, 2: 89.0, 3: 86.5, 4: 80.0}, 'Science': {0: 78, 1: 90, 2: 95, 3: 85, 4: 89}, 'History': {0: 88.0, 1: 92.0, 2: 85.0, 3: 91.0, 4: 89.0}}
[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

In [ ]:
# 강사님 풀이

In [38]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Math": [85, np.nan, 88, 90, 76],
    "English": [92, 85, 89, np.nan, 80],
    "Science": [78, 90, 95, 85, 89],
    "History": [88, 92, 85, 91, np.nan]
})

In [31]:
# info()를 통해서 확인
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Math     4 non-null      float64
 2   English  4 non-null      float64
 3   Science  5 non-null      int64
 4   History  4 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 328.0+ bytes

In [33]:
# df1.columns -> columns 확인
df1.columns

Index(['Name', 'Math', 'English', 'Science', 'History'], dtype='object')

In [39]:
# 숫자 열에 대해 결측값을 각 열의 평균값으로 대체
df2 = df1.copy()
columns = ['Math', 'English', 'Science', 'History']
for column in columns:
    df2[column].fillna(df2[column].mean(),inplace=True)
df2

      Name   Math  English  Science  History
0    Alice  85.00     92.0       78     88.0
1      Bob  84.75     85.0       90     92.0
2  Charlie  88.00     89.0       95     85.0
3    David  90.00     86.5       85     91.0
4      Eve  76.00     80.0       89     89.0

In [37]:
# df1 데이터 프레임에서 숫자형 데이터 타입을 가진 열들만 선택
df2 = df1.copy()
for column in df2.select_dtypes(include=[np.number]).columns:
    df1[column].fillna(df2[column].mean(),inplace=True)
df

      국어  영어   수학  과학  사회
s1   결시자  85   85  90  90
s2    85  80  결시자  85  85
s3    80  75   75  80  80
s4   결시자  70   70  75  75
s5    70  65   65  70  70
s6   결시자  60  결시자  65  65
s7    60  55   55  60  60
s8    55  50   50  55  55
s9    50  45   45  50  50
s10   45  40   40  45  45

In [40]:
# 배열로 변환
array1 = df2.to_numpy()
# array1 = df2.values     # 같은 결과값
print(array1)

# 딕셔너리로 변환
# (orient='list') 생략가능 그냥 ('list')만 해도됨
dict1 = df2.to_dict(orient='list')
print(dict1)

# 리스트로 변환
list1 = df2.values.tolist()
print(list1)

<bound method DataFrame.to_numpy of       Name   Math  English  Science  History
0    Alice  85.00     92.0       78     88.0
1      Bob  84.75     85.0       90     92.0
2  Charlie  88.00     89.0       95     85.0
3    David  90.00     86.5       85     91.0
4      Eve  76.00     80.0       89     89.0>
{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 'Math': [85.0, 84.75, 88.0, 90.0, 76.0], 'English': [92.0, 85.0, 89.0, 86.5, 80.0], 'Science': [78, 90, 95, 85, 89], 'History': [88.0, 92.0, 85.0, 91.0, 89.0]}
[['Alice', 85.0, 92.0, 78, 88.0], ['Bob', 84.75, 85.0, 90, 92.0], ['Charlie', 88.0, 89.0, 95, 85.0], ['David', 90.0, 86.5, 85, 91.0], ['Eve', 76.0, 80.0, 89, 89.0]]

Task4_0527. df2에서 아래와 같이 데이터 필터링 및 정렬 후 배열, 딕셔너리, 리스트로 변환하여 출력하세요.
- Math 점수가 80 이상인 학생만 선택
- English 점수를 기준으로 내림차순 정렬

In [47]:
df2 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Math": [85, 79, 88, 90, 76],
    "English": [92, 85, 89, 93, 80],
    "Science": [78, 90, 95, 85, 89],
    "History": [88, 92, 85, 91, 84]
})

# 수학점수가 80이상인 셀 선택
df_filtered = df2[df2["Math"] >= 80]
# 영어점수 내림차순 정렬
# default 값은 오름차순 ascending=False -> 내림차순 변경
df_sorted = df_filtered.sort_values(by="English", ascending=False)

# 배열로 변환
array2 = df_sorted.to_numpy()
print(array2)

# 딕셔너리로 변환
dict2 = df2.to_dict(orient='list')
print(dict2)

# 리스트로 변환
list2 = df_sorted.values.tolist()
print(list2)

[['David' 90 93 85 91]
 ['Alice' 85 92 78 88]
 ['Charlie' 88 89 95 85]]
{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 'Math': [85, 79, 88, 90, 76], 'English': [92, 85, 89, 93, 80], 'Science': [78, 90, 95, 85, 89], 'History': [88, 92, 85, 91, 84]}
[['David', 90, 93, 85, 91], ['Alice', 85, 92, 78, 88], ['Charlie', 88, 89, 95, 85]]

Task5_0527. df3에서 각 학생의 평균 점수 계산 후 배열, 딕셔너리, 리스트로 변환하여 출력하세요.

In [69]:
df3 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice", "Bob", "Charlie", "David", "Eve"],
    "Subject": ["Math", "Math", "Math", "Math", "Math", "English", "English", "English", "English", "English"],
    "Score": [85, 79, 88, 90, 76, 92, 85, 89, 93, 80]
})

# 각 학생의 평균 점수 계산
df3_avg = df3.groupby('Name')['Score'].mean()
# df3_avg = df3['Score'].groupby(df3['Name']).mean()
print(df3_avg)

# 배열 변환
array_avg = df3_avg.to_numpy()
print(array_avg)

# 딕셔너리 변환
dict_avg = df3_avg.to_dict()
print(dict_avg)

# 리스트 변환
list_avg = df3_avg.tolist()
print(list_avg)

In [ ]:
# 강사님 풀이

In [70]:
# aggfunc='mean' -> 평균 구하기 sum... 등등 쓸 수 있음.
df3.pivot_table(index='Name', columns='Subject',values='Score',aggfunc='mean')

Subject  English  Math
Name
Alice         92    85
Bob           85    79
Charlie       89    88
David         93    90
Eve           80    76

In [75]:
# reset_index()를 통해서 인덱스를 만들어줌. 각각의 칼럼으로 만들어줌.
# Subject가 하나의 칼럼인데 사용하기 애매해짐.
# 5번을 통해서 Subject를 삭제
df3_pivot_table = df3.pivot_table(index='Name', columns='Subject',values='Score',aggfunc='mean').reset_index()
df3_pivot_table.columns.name = None
print(df3_pivot_table)

      Name  English  Math
0    Alice       92    85
1      Bob       85    79
2  Charlie       89    88
3    David       93    90
4      Eve       80    76

In [51]:
# 배열 변환
array_avg = df3_avg.to_numpy()
print(array_avg)

# 딕셔너리 변환
dict_avg = df3_avg.to_dict()
print(dict_avg)

# 리스트 변환
list_avg = df3_avg.tolist()
print(list_avg)

[88.5 82.  88.5 91.5 78. ]
{'Alice': 88.5, 'Bob': 82.0, 'Charlie': 88.5, 'David': 91.5, 'Eve': 78.0}
[88.5, 82.0, 88.5, 91.5, 78.0]

Task6_0527. df4에서 특정 열의 데이터 타입을 변환한 후 변환된 타입을 확인하세요.

In [ ]:
df4 = pd.DataFrame({
    'A': ['1', '2', '3', '4'],
    'B': ['5.1', '6.2', '7.3', '8.4'],
    'C': ['2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01']
})

# 딕셔너리 변환
df4_dict = df4.to_dict()

# 리스트 변환
df4_list = df4.values.tolist()

# 출력
print(df4_dict)
print(type(df4_dict))
print(df4_list)
print(type(df4_list))

{'A': {0: '1', 1: '2', 2: '3', 3: '4'}, 'B': {0: '5.1', 1: '6.2', 2: '7.3', 3: '8.4'}, 'C': {0: '2021-01-01', 1: '2021-02-01', 2: '2021-03-01', 3: '2021-04-01'}}
<class 'dict'>
[['1', '5.1', '2021-01-01'], ['2', '6.2', '2021-02-01'], ['3', '7.3', '2021-03-01'], ['4', '8.4', '2021-04-01']]
<class 'list'>

In [ ]:
# 강사님 풀이

In [78]:
df4 = pd.DataFrame({
    'A': ['1', '2', '3', '4'],
    'B': ['5.1', '6.2', '7.3', '8.4'],
    'C': ['2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01']
})

# 'A' 열을 정수형(int)으로 변환
df4['A'] = df4['A'].astype(int)

# 'B' 열을 부동 소수점(float)으로 변환
df4['B'] = df4['B'].astype(float)

# 'C' 열을 datetime 형식으로 변환
df4['C'] = pd.to_datetime(df4['C'])

# 데이터 타입 확인
print(df4.dtypes)

A             int64
B           float64
C    datetime64[ns]
dtype: object

Task7_0527. df5에서 나이가 25 이상인 행을 출력하세요.

In [84]:
df5 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
})

# 나이가 25 이상인 행 선택
df_filtered = df5[df5['Age'] >= 25]

# # 나이순 오름차순 정렬
# df_sorted = df_filtered.sort_values(by='Age')

# 출력
print(df_filtered)
# print()
# print(df_sorted)

    Name  Age         City
1    Bob   27  Los Angeles
3  David   32      Houston
4    Eve   29      Phoenix

    Name  Age         City
1    Bob   27  Los Angeles
4    Eve   29      Phoenix
3  David   32      Houston

In [ ]:
# 강사님 풀이

In [85]:
subset = df5[df5['Age'] >= 25]
print("\n나이가  25 이상인 행: \n \n", subset)

나이가  25 이상인 행:

     Name  Age         City
1    Bob   27  Los Angeles
3  David   32      Houston
4    Eve   29      Phoenix