Task1_0620. 네이버 영화 순위 사이트에서 영화제목, 가격, 타입(구매 or 대여) 정보를 가져와서 TITLE, PRICE, TYPE 3개의 컬럼과 100개의 데이터포인트로 구성된 데이터프레임을 출력하세요.

In [15]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3',
    'Accept-Language': 'en-US,en;q=0.9',
    'Referer': 'http://example.com',
}

url = 'https://serieson.naver.com/v3/movie/ranking/realtime'

# HTTP GET as 요청을 보냄
response = requests.get(url, headers=headers)
response

# HTTP GET 요청이 성공적으로 전달되면 코드를 가져오기
if response.status_code == 200:
    # HTML코드를 파싱
    soup = BeautifulSoup(response.text, 'html.parser')

In [16]:
# title = soup.find_all(class_='Title_title__s9o0D')
# for t in title:
#     print(t.text)

In [17]:
titles = soup.find_all(class_='Title_title__s9o0D')
title = [title.text.strip() for title in titles]
df_titles = pd.DataFrame({'Title':title})                
df_titles

                                 Title
0     인사이드 아웃(패키지상품 : 더빙판 + 부가영상 추가증정)
1                            원피스 필름 레드
2   어벤져스: 엔드게임(패키지: 자막판+더빙판+코멘터리+부가영상)
3                      명탐정 코난 VS 괴도 키드
4         엘리멘탈(패키지: 자막판+더빙판+부가영상+코멘터리)
..                                 ...
95                                 랑데부
96                                  캠핑
97                                 서울역
98                  극장판 명탐정 코난: 순흑의 악몽
99           곡성(哭聲)(2.35:1 극장판부가영상 제공)

[100 rows x 1 columns]

In [18]:
# title = soup.find_all(class_='Price_text__pRk_f')
# for t in title:
#     print(t.text)

In [19]:
types = soup.find_all(class_='Price_text__pRk_f')
type = [type.text.strip() for type in types]
df_type = pd.DataFrame({'Type':type})       
df_type

   Type
0    구매
1    대여
2    구매
3    대여
4    구매
..  ...
95   구매
96   구매
97   구매
98   대여
99   구매

[100 rows x 1 columns]

In [20]:
# prices = soup.find_all(class_='Price_price__GqXqo')
# for p in prices:
#     price_text = p.text.replace('캐시', '')  # '캐시'를 빈 문자열로 대체하여 제거
#     print(price_text)

In [21]:
# prices = soup.find_all(class_='Price_price__GqXqo')
# for p in prices:
#     price_text = p.text.replace('캐시', '원')  # '캐시'를 '원'으로 대체
#     print(price_text)

In [22]:
# prices = soup.find_all(class_='Price_price__GqXqo')
# for p in prices:
#     price_text = p.text.replace('캐시', '').strip()  # '캐시' 제거 후 공백 제거
#     price_int = int(price_text.replace(',', ''))  # 쉼표 제거 후 int로 변환
#     print(price_int)

In [23]:
# prices = soup.find_all(class_='Price_price__GqXqo')
# prices_list = []
# for p in prices:
#     price_text = p.text.replace('캐시', '').strip()
#     price_int = int(price_text.replace(',', ''))
#     price_list.append(price_int)
# df_prices = pd.DataFrame({'Price': price_list})
# df_prices

In [24]:
price_list = []

for tag in soup.find_all(class_='Price_price__GqXqo'):
    if 'Price_delete__EoEjk' in tag['class']:
        # 할인 전 가격일 경우 처리하지 않음
        continue
    else:
        # 정상적인 가격 데이터 추출
        price = tag.text.strip()
        # '캐시' 문자 제거 후 정수로 변환
        price = int(price.replace('캐시', '').replace(',', ''))
        price_list.append(price)

df_prices = pd.DataFrame({'Price': price_list})

In [25]:
df_prices

    Price
0    7150
1    1540
2    5500
3   11000
4    7150
..    ...
95   1200
96   1200
97   1000
98   1540
99   5500

[100 rows x 1 columns]

In [28]:
df_naver_series = pd.concat([df_titles, df_type, df_prices], axis=1)

# 합쳐진 데이터 프레임 출력
df_naver_series

                                 Title Type  Price
0     인사이드 아웃(패키지상품 : 더빙판 + 부가영상 추가증정)   구매   7150
1                            원피스 필름 레드   대여   1540
2   어벤져스: 엔드게임(패키지: 자막판+더빙판+코멘터리+부가영상)   구매   5500
3                      명탐정 코난 VS 괴도 키드   대여  11000
4         엘리멘탈(패키지: 자막판+더빙판+부가영상+코멘터리)   구매   7150
..                                 ...  ...    ...
95                                 랑데부   구매   1200
96                                  캠핑   구매   1200
97                                 서울역   구매   1000
98                  극장판 명탐정 코난: 순흑의 악몽   대여   1540
99           곡성(哭聲)(2.35:1 극장판부가영상 제공)   구매   5500

[100 rows x 3 columns]

In [5]:
# Task1_0620. 네이버 영화 순위 사이트에서 영화제목, 가격, 타입(구매 or 대여) 정보를 가져와서 TITLE, PRICE, TYPE 3개의 컬럼과 100개의 데이터포인트로 구성된 데이터프레임을 출력하세요.
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

# URL 설정
url = 'https://serieson.naver.com/v3/movie/ranking/realtime'

# HTTP GET 요청
response = requests.get(url)
response.raise_for_status()  # 요청이 성공했는지 확인

# BeautifulSoup을 사용하여 HTML 파싱
soup = BeautifulSoup(response.content, 'html.parser')

# 영화 제목과 가격을 저장할 리스트
titles = []
prices = []
types = []

# 영화 제목과 가격 추출
movies = soup.select('.RankingList_ranking_list__N4QsH > li')

for movie in movies:
    title_tag = movie.select_one('.Title_title__s9o0D')
    if title_tag:
        title = title_tag.get_text(strip=True)
    
        # 가격 및 타입 추출
        price_items = movie.select('.Price_price_item__tOOqb')
        for price_item in price_items:
            type_tag = price_item.select_one('.Price_text__pRk_f')
            price_tag = price_item.select_one('.Price_price__GqXqo')
            if type_tag and price_tag:
                type_text = type_tag.get_text(strip=True)
                price = price_tag.get_text(strip=True)
                
                # 가격에서 "캐시" 및 SVG 태그 제거
                price = re.sub(r'캐시.*', '', price).strip()
                
                titles.append(title)
                prices.append(price)
                types.append(type_text)

# 데이터프레임 생성
df = pd.DataFrame({
    'Title': titles,
    'Price': prices,
    'Type': types
})

# 데이터프레임 출력
df

                               Title   Price Type
0   인사이드 아웃(패키지상품 : 더빙판 + 부가영상 추가증정)   7,150   구매
1                                콩나물   1,000   구매
2                     태극기 휘날리며 - 특별판  10,000   구매
3                                설계자  11,000   대여
4                          원피스 필름 레드   1,540   대여
..                               ...     ...  ...
81                               마스크   1,300   대여
82                         사운드 오브 뮤직   5,500   구매
83                        마지막 한 걸음까지     500   구매
84                            흑인 오르페     500   구매
85                               수집가   2,500   대여

[86 rows x 3 columns]

In [33]:
# csv파일 다시 불러오기
df = pd.read_csv('articles.csv')
df

                                              Atticle
0             행안부 차관, 고창 '은퇴자 마을' 방문…"지역 소멸 대안될 수 있어"
1                       순천 기회발전특구 지정, K-콘텐츠 전진기지 육성한다
2                국회 복지위, 복지부 장‧차관 현안질의 불참에 26일 청문회 개최
3                野 '노란봉투법·양곡법' 상임위 상정…'채해병 특검법' 소위 통과
4                 성북구 꿈빛극장 29~30일 가족극 '고래바위에서 기다려' 공연
5               “이재명 대항마 어디 없나”…‘어대명’ 분위기에 野전대 흥행 빨간불
6                      올 여름 어떡하나..174년만에 최고로 뜨거운 지구 外
7                국민의힘 엄태영 "공영방송 친민주당 방송 만들 바엔 민영화" 논란
8                       양천구, 폭염 대비 현업근로자 보냉장구 600구 지원
9   북러 정상회담 기간 ‘죽음의 천사’ AC-130J 헬파이어 미사일 쏘며 한미연합공중...
10               배달앱서 사라진 '맥날 세트 메뉴'.. 이유는 "감자튀김 없어서"
11          ‘쌍방울 대북송금’ 이재명 공소장 보니…“보고 있었다” 검찰 판단 근거는?
12               與 저출생대응법 당론발의…野법안과 다른 새 간호사법도 제출(종합)
13               노봉법, 양곡법, 간호법..'거부권-폐기' 법안 속속 되살리는 野
14                    김정호 "부산·경남 행정통합 추진은 정치적 책임 회피용"
15                    노동약자 챙긴다더니…`미조직근로자` 저출생 대책은 없었다
16                                        “많이·빠르게 감소”
17                    한동훈 "23일 출마 선언"...'민주당의 아버지' 여진
18                         윤석열 ‘개인폰’ 통화 기록, 왜 자꾸 나올까?
19                     한동훈 23일 당대표 출마 선언…이재명 연임 도전 수순
20  野, 채상병특검 청문회 불출석 증인 ‘무더기 고발’ 예고…“신원식·김계환만 사유서 제출”
21          나경원 "근본 깨는 이재명, 대한민국 비명횡사..무조건 막아야, 곧 결심"
22            박원석 "원희룡 출마? 용산 참전신호"...김근식 "결선투표 노린 듯"
23  나경원 “당 대표는 대통령과의 갈등이 겉으로 드러나면 안 돼…차별화해 대권 가겠다는...
24  최진녕 변호사 / 서용주 전 더불어민주당 상근부대변인 - 원 구성 놓고 여야 입장 ...
25                                                뉴스홈
26                                                 사회
27                                                 정치
28                                                 경제
29                                                 국제
30                                                 문화
31                                                 IT
32                                                 포토
33                                             제휴 언론사
34                                               배열이력
35                                               전체뉴스
36                                                 연재
37                                               팩트체크

Task2_0620. url = 'https://news.daum.net/politics#1'은 정치기사 1페이지인데 10페이지에 있는 기사를 모두 출력하세요.

In [6]:
# 문제의 주소에서는 #다음에 크롤링이 안되서 url = 'https://news.daum.net/breakingnews/politics?page= 여기서 처리.
import requests
from bs4 import BeautifulSoup
import re

for j in range(1, 11):
    #https://news.daum.net/breakingnews/politics?page=1
    url = f'https://news.daum.net/breakingnews/politics?page={j}'
    print(url)
    
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    lines = soup.find_all('a',class_="link_txt")
    lines = lines[7:-21]
    for i, tag in enumerate(lines, 1):
        text = tag.get_text().strip().replace(',', '')
        matches = re.findall('[가-힣0-9]+', text)
        print(f"{i}. {' '.join(matches)}")
    print(f'페이지수: {j}')

https://news.daum.net/breakingnews/politics?page=1
1. 박찬대 권익위 명품백 답변 에 어처구니 없는 헛소리
2. 북 러 군사 협력 범위 불분명 생각보다 더 장기적 더 위험
3. 경기도 무장애 관광지 컨설팅 사업 참여 관광지 모집
4. 정유라 조민 대법 판결 남았는데 이 타이밍에 결혼을
5. 전략사령부 올 하반기 창설 사령관은 육 해 공군 장성 순환보직
6. 게시판 식약처 의약품안전관리원 약물안전캠페인
7. 원희룡 23일 국회서 당대표 출마 선언 한동훈과 같은날
8. 유승민 전당대회 불출마 무의미한 도전
9. 윤상현 한동훈 사석서 그 사람 이라고 신뢰 관계 바닥
10. 김현기 서울시의장 몽골 울란바토르에 소방차 10대 전달
11. 탈북단체 대북전단 30만장 살포
12. 북한 6 25 미제 반대 투쟁의 날 앞두고 원수 격멸 의지 굳건
13. 현대 폴란드 국제해양 안보포럼 서 잠수함 플랫폼 제안
14. 유승민 국민의힘 당대표 경선 불출마 절박함이 시작될 때 역할 하겠다 상보
15. 박찬대 건희위원회로 전락한 권익위 고무줄 청탁금지법 지적
페이지수: 1
https://news.daum.net/breakingnews/politics?page=2
1. 대통령실 야 단독소집 운영위 불참키로 야 증인 채택할듯
2. 속보 무의미한 도전이라 결론 유승민 당대표 불출마
3. 속보 유승민 전당대회 불출마 무의미한 도전
4. 원희룡 한동훈과 같은 날 같은 곳에서 당대표 출마 선언
5. 원희룡 23일 국회서 출마선언 과 1시간 간격 같은 날 같은 장소
6. 우크라 무기지원은 러 행동에 달려 155 포탄 등 방산 대기중
7. 박찬대 오늘 채해병 특검 청문회 윤 감추려는 진실 드러날 자리
8. 원희룡 모레 대표 출마선언 한동훈과 한날 출사표
9. 속보 유승민 국민의힘 전대 불출마 무의미한 도전
10. 당 대표 출마 준비중인 한동훈 전 비대위원장 응원 화환
11. 즐비하게 놓여져 있는 한동훈 응원 화환
12. 당 대표 출마 준비중인 한동훈 전 비대위원장 응원화환
13. 박찬대 해병대원 특검법 또다시 거부한다면 범죄자라 자백한 것으로 여길 것
14. 한동훈 전 비대위원장 사무실 앞 응원 화환
15. 유승민 당대표 불출마 무의미한 도전
페이지수: 2
https://news.daum.net/breakingnews/politics?page=3
1. 탈북민단체 어젯밤 파주서 대북전단 30만장 살포
2. 통합위 27일 2024 국민통합 컨퍼런스 개최
3. 속보 유승민 대표 경선 불출마 무의미한 도전이라 결론
4. 탈북민단체 어젯밤 대북 전단 30만 장 살포 북한 대응 주목
5. 유승민 당대표 불출마 선언 무의미한 도전
6. 자유북한운동연합 대북전단 살포
7. 북한 우크라전 끝나면 러시아에 팽
8. 북한도발사 다큐 시즌2 방영 38선 국지전 도발 등 조명
9. 원희룡 모레 국회서 대표 출마선언 한동훈과 한날 출사표
10. 유승민 전당대회 불출마 선언 무의미한 도전
11. 국회기후변화포럼 개원 총회 참석한 허용수 대표이사
12. 2024 국회기후변화포럼 개원 총회
13. 2024 국회기후변화포럼 개원 총회
14. 이희완 보훈차관 보훈위탁병원 비상진료체계 현장 점검
15. 추미애 김용태 정혜경 이소영 국회기후변화포럼 개원 총회
페이지수: 3
https://news.daum.net/breakingnews/politics?page=4
1. 여야 의원들이 함께 한 국회기후변화포럼 개원 총회
2. 발언하는 정희용 국회기후변화포럼 공동대표
3. 발언하는 한정애 국회기후변화포럼 공동대표
4. 사실은 이렇습니다 농식품부 2025년 농식품 바우처 예산 아직 확정되지 않아
5. 사실은 이렇습니다 기재부 결혼 특별세액공제 구체적 내용 미확정
6. 사실은 이렇습니다 행안부 지하차도 안전관리 강화 위해 지속 노력
7. 여야가 함께 기후위기 대응을
8. 자유북한운동연합 지난 밤 대북 전단 30만장 살포
9. 한 폴 50 항공정비 협력합의 수출 후 도 확실한 방산
10. 자유북한운동연합 대북 전단 30만장 살포
11. 유승민 당대표 경선 출마 안 한다 무의미한 도전이라 결론
12. 속보 유승민 당대표 불출마 무의미한 도전 절박함 시작될 때 역할
13. 보령시 해수욕장 개장 대비 원산지 표시 특별점검
14. 21 원거리 작전 공중급유 성공 비행시험 3분의 1 순항
15. 영등포구 상가 등 소상공인 도로점용료 25 감면
페이지수: 4
https://news.daum.net/breakingnews/politics?page=5
1. 성능 가격 확장성 21 전투기서도 방산 성공신화 잇는다
2. 한동훈 당대표 공식 출마선언 앞두고 응원 화환 잇따라
3. 6세대 진화 가능한 21 낮은 운용유지비도 장점
4. 현대중공업 국제해양 안보포럼 참가
5. 속보 6월 1 20일 수출 8 5 증가 무역흑자 15억달러
6. 유승민 전당대회 불출마 선언 무의미한 도전
7. 한동훈 선거캠프 앞 놓인 지지자들의 응원 화환
8. 어차피 대표는 한동훈
9. 한동훈 당대표 출마선언 앞두고 잇따르는 응원 화환
10. 유승민 7 23 전당대회 불출마하기로
11. 한동훈 선거캠프 앞 놓인 응원 화환들
12. 유승민 당 대표 불출마 절박함 시작될 때 역할
13. 조태열 외교장관 러 북 조약 개탄스럽게 생각
14. 유승민 전당대회 불출마 무의미한 도전
15. 속보 유승민 전대 불출마 무의미한 도전
페이지수: 5
https://news.daum.net/breakingnews/politics?page=6
1. 유승민 국민의힘 대표 경선 불출마 무의미한 도전이라고 결론
2. 강남구 1인가구 커뮤니티센터 확장 이전 전국 최고 시설로
3. 유승민 국민의힘 대표 경선 불출마 무의미한 도전
4. 윤상현 한동훈 윤에 면피성 전화 신뢰관계 거의 바닥
5. 포토 안경 고쳐쓰는 이재명 대표
6. 국민과 함께하는 동행 국민통합 컨퍼런스 개최
7. 고양시 북한 오물 풍선 살포 계기로 생물테러 대비 훈련
8. 속보 유승민 국민의힘 전당대회 불출마 망한다는 절박함 시작될 때 역할 하겠다
9. 정치쇼 박주민 청문회서 박정훈 대령 진술 이종섭도 입 열 수 밖에
10. 속보 무의미한 도전 유승민 대표 경선 불출마
11. 포토 최고위 참석하는 이재명 박찬대
12. 유승민 불출마 무의미한 도전이라고 결론
13. 전현희 이재명은 민주당 아버지 믿음의 또 다른 표현
14. 사실은 이렇습니다 과기정통부 출연연 지원 육성 관리 방안 6월 말 발표 예정
15. 사실은 이렇습니다 과기정통부 양자통신 기술 확보와 보안 강화 쪽 모두 지원
페이지수: 6
https://news.daum.net/breakingnews/politics?page=7
1. 사실은 이렇습니다 행안부 민생 안정 주요사업 위축되지 않도록 지자체와 적극 협력
2. 조국 모든 의혹 윤 대통령에 모여 맥베스와 아내의 최후 다가와
3. 유승민 국힘 당대표 불출마 선언 무의미한 도전
4. 유승민 당 대표 불출마 선언 무의미한 도전
5. 유승민 무의미한 도전 전당대회 불출마 선언
6. 조태열 유엔 안보리서 북러 조약은 명백한 결의 위반 국제사회 단결해야
7. 김경일 파주시장 시민이 체감하는 적극행정 확산시켜 나갈 것
8. 포토 최고위 발언하는 박찬대 원내대표
9. 전략사령부 올 하반기 창설 사령관은 육해공 순환
10. 속보 국민의힘 유승민 당대표 불출마 선언 무의미한 도전
11. 원희룡 23일 국회서 출마선언 한동훈과 같은 날 같은 장소
12. 김경일 파주시장 국회서 대북전단 살포 중단 호소
13. 신원식 폴란드서 50 전력화 확인 한 폴 방산협력 굳히기 돌입
14. 정부 우크라에 155 포탄 지원할까 살상 무기 지원 검토
15. 유승민 대표 경선 불출마 무의미한 도전이라고 결론
페이지수: 7
https://news.daum.net/breakingnews/politics?page=8
1. 조태열 외교장관 북러 조약 유엔 안보리 결의 위반 개탄스러워
2. 유승민 전당대회 불출마 선언 무의미한 도전이라 결론 내려
3. 오늘 원구성 대응 전략 논의 상임위 7개 수용
4. 국방장관 방사청장 폴란드 50 운용 점검 유지보수 협력
5. 유승민 당대표 경선 출마하지 않겠다 무의미한 도전
6. 세계 반도체 싸움 인재 용수 전력망 공급 정부가 나서야 인터뷰
7. 탈북민단체 어젯밤 대북 전단 30만장 살포 북한 대응 주목
8. 원희룡 23일 전당대회 출마 기자회견 한동훈과 같은 날
9. 유승민 전당대회 불출마 선언 무의미한 도전이라고 결론
10. 김종민 야6당 교섭단체 안 만들면 21명 의원 전부 깍두기 된다
11. 이준석 홍준표의 이재명 동탁 비유에 판단 잘못해 일 그르친 원소로 보여
12. 속보 유승민 전당대회 불출마 무의미한 도전
13. 뉴스파이팅 김재원 원희룡 용산 친윤에서 밀어주고 있다
14. 한미동맹엔 없지만 북중동맹에 있는 것 새로운 북러 조약에도 스프
15. 광주 전남지역 하나로마트 양파 마늘 20 35 할인
페이지수: 8
https://news.daum.net/breakingnews/politics?page=9
1. 파주보건소 친환경 건물로 재탄생 국 도비 12억원 확보
2. 해외 당원도 보낸 한동훈 응원 화환
3. 여수 묘도지구 수소산업 클러스터 기회발전특구 지정
4. 부안 지진 중대본 1단계 10일 만에 해제 시설피해 1196건
5. 에서 푸틴으로 김정은의 환승외교 도박 성공할까 박수찬의
6. 속보 유승민 전대 불출마 무의미한 도전
7. 영상 추미애 탄핵 6행시 6선 의심스러운 저급함에 민망
8. 신원식 폴란드 민스크 공군기지 방문 50 전력화 확인
9. 부산시의회 24시 부산시민에게 맑은 물 공급하려면
10. 진도군 22일 씬나부네 흥나는 놀이터 연다
11. 언론은 검찰 애완견 거칠어진 이재명의 속내는 불안감
12. 전현희 이재명은 민주당의 아버지 믿음의 또 다른 표현
13. 전쟁상태 지체없이 군사 원조 북러 사실상 동맹 복원
14. 이준석은 양반 이었다 신평 한동훈 이준석보다 과 더 심하게 충돌할 것
15. 외교부 오늘 주한러시아대사 초치할 듯 북러 조약 항의
페이지수: 9
https://news.daum.net/breakingnews/politics?page=10
1. 윤상현 원희룡 날 돕겠다고 했는데 한동훈 이재명 구속도 총선도 실패
2. 인천 29개 해수욕장 22일부터 차례로 개장
3. 구례신활력네트워크미래포럼 출범
4. 원희룡 한동훈과 같은날 당권 기자회견 1시간차 정면승부
5. 강원도의회 후반기 의장 후보 김시성 군림하지 않는 의장
6. 대표적 군사 규제 민통선 강원도 국회 규제 개선 공조
7. 한동훈 사무실 앞 응원 꽃바구니
8. 한동훈 사무실 앞 응원 꽃바구니
9. 조태열 유엔 무대서 북러 조약 규탄 명백한 안보리 결의 위반 종합
10. 한동훈 전 비대위원장 사무실 앞 응원 화환
11. 조국 아무도 윤석열을 구해주지 못한다 맥베스와 아내의 최후 오고 있어
12. 한동훈 선거 캠프 앞 응원 화환
13. 한동훈 선거 캠프 앞 응원 화환
14. 한동훈 선거 캠프 앞 응원 화환
15. 유시민 한동훈에 언론 하이에나가 물어뜯는 날 곧 온다 경고
페이지수: 10

Task3_0620. 앞에서 출력한 기사 리스트를 pandas 데이터프레임으로 변환 후 csv 파일로 저장 후 다시 불러오세요.

In [2]:
# 3번 과제에 대한 풀이 참고하세요.
import requests as rq
from bs4 import BeautifulSoup
import pandas as pd

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}

base_url = f'https://news.daum.net/breakingnews/politics?page='

# 빈 리스트를 만들어 기사를 저장할 준비를 합니다
all_articles = []

# 여러 페이지를 순회하며 기사 제목을 추출
for page_num in range(1, 11):
    url = f'{base_url}{page_num}'
    r = rq.get(url, headers=headers)
    html = r.text
    soup = BeautifulSoup(html, 'html.parser')

    # 기사 제목 추출
    lines = soup.find_all('a', class_="link_txt")
    lines = lines[7:-21]
    articles = [line.text.strip() for line in lines]

    # 추출한 기사 제목을 전체 기사 리스트에 추가
    all_articles.extend(articles)

# 인덱스 생성
indices = range(1, len(all_articles) + 1)

# 데이터프레임 생성
df = pd.DataFrame({'Index': indices, 'Article': all_articles})

df.to_csv('daum_politics_articles.csv', index=False)
df = pd.read_csv('daum_politics_articles.csv')
df

     Index                                      Article
0        1              채상병 청문회 시작…이종섭·신범철·임성근 증인 선서 거부
1        2                  북한군, 세 번째 MDL 침범…軍 경고사격에 퇴거
2        3                  尹 대통령 국정 지지율 26%... 지난주와 동일
3        4        '당권 도전' 나경원 "당대표 선거 앞두고 줄세우는 정치 타파해야"
4        5  [속보] 이재명 "채 해병 특검법 1주기 전 통과.. 윤 대통령 거부 말아야"
..     ...                                          ...
145    146                [속보] 합참 "어제 오전 11시쯤 북한군 또 침범"
146    147          유시민, 한동훈 향해 "You win..그래, 당신 팔뚝 굵어"
147    148    [속보]  北, 어제 또 DMZ 작업 중 군사분계선 침범…2주 사이 3차례
148    149              法 "노소영 아트센터 나비, SK건물 퇴거·10억 배상"
149    150           나경원→한동훈→원희룡, 23일 국회에서 1시간 간격 ‘출사표’

[150 rows x 2 columns]